---
abstract: 'Report on SSIS packages by Ded MedVed'
author:
  - 'Ded MedVed <dedmedved@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SSIS-Package
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Data::Dumper: 0
  Data::Printer: 0
  IPC::System::Simple: 0
  List::MoreUtils: 0
  List::Util: 0
  Mouse: 0
  Test::Deep: 0
  Test::More: 0
  XML::CompactTree::XS: 0
  XML::LibXML::Reader: 0
  XML::Simple: 0
  autodie: 0
  indirect: 0
  perl: 0
  version: 0
version: 1.00_08
